# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [blood, Army]
patreon: # https://www.patreon.com/posts/22854182
open_collective: # https://justinfamily.family.blog/
ko_fi: # Replace with a single Ko-fi Alexa
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel npm install --save @babel/runtime
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username https://opensea.io
issuehunt: # Replace with a single IssueHunt username https://pollenlondon.com/
otechie: # Replace with a single Otechie username https://G.page/justinsmith33583
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://Victoriasecrete.com', 'https://libertymutal.com']
